= Step 0: Quickstart

=== Prerequisites
----
sudo apt update
sudo apt upgrade
sudo apt-get install virtualbox docker.io
----

=== Create a Directory
----
mkdir ~/11steps
cd ~/11steps
----

=== git clone materials
----
git clone https://github.com/tiagordc/11stepsawesome
----

=== Make a directory for executables
----
mkdir bin
cd bin
----

=== Download minikube & kubectl

----
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.7.2/minikube-linux-amd64

chmod +x minikube

./minikube version

curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl 

chmod +x kubectl

cd ..
----

=== Set Environment Variables
----
export MINIKUBE_HOME=/home/tiago/11steps;
export PATH=$MINIKUBE_HOME/bin:$PATH
export KUBECONFIG=$MINIKUBE_HOME/.kube/config
export KUBE_EDITOR="code -w"
----

=== Startup Minikube
----
minikube --profile 11steps config set memory 6144 
minikube --profile 11steps config set cpus 2 
minikube --profile 11steps config set vm-driver virtualbox 
minikube --profile 11steps config set kubernetes-version v1.14.0
minikube start --profile 11steps
----

=== Run kubectl commands
----
kubectl cluster-info
kubectl get nodes
kubectl get nodes --show-labels
kubectl get namespaces
kubectl config view
cat $KUBECONFIG
kubectl config current-context
minikube --profile 11steps config view
kubectl get pods --all-namespaces
kubectl get pods --all-namespaces --show-labels
kubectl get pods --all-namespaces -o wide
----

=== View dashboard
----
minikube --profile 11steps dashboard

kubectl proxy --address='0.0.0.0' --disable-filter=true
curl http://your_api_server_ip:8001/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/
----

TIP: "minikube profile 11steps" will set that as the default, make it sticky, therefore you will not have to type "minikube --profile 11steps" for subsequent commands

=== Deploy Something
----
kubectl create deployment myapp --image=quay.io/burrsutter/myboot:v1

kubectl get events
kubectl get events --sort-by=.metadata.creationTimestamp
kubectl get all
kubectl logs -l app=myapp

kubectl expose deployment myapp --port=8080 --type=LoadBalancer

kubectl get services
----

=== Talk to App
----
minikube --profile 11steps ip

minikube --profile 11steps service myapp --url

curl http://192.168.99.100:31045

minikube --profile 11steps service myapp

curl $(minikube -p 11steps ip):$(kubectl get service/myapp -o jsonpath="{.spec.ports[*].nodePort}" -n default)

watch kubectl get pods

while true; do curl $(minikube -p 11steps ip):$(kubectl get service/myapp -o jsonpath="{.spec.ports[*].nodePort}" -n default); sleep .3; done

kubectl scale deployment myapp --replicas=3
----

=== Update the App
----
kubectl set image deployment/myapp myboot=quay.io/burrsutter/myboot:v2
----

=== Update the App Again
----
kubectl set image deployment/myapp myboot=quay.io/burrsutter/quarkus-demo:1.0.0
----

=== Clean Up
----
kubectl delete service myapp

kubectl delete deployment myapp

minikube --profile 11steps stop

ls -lh ~/11steps/.minikube/machines/11steps

minikube --profile 11steps delete 
----

=== Configure Env for Docker 
----
$ minikube --profile 11steps docker-env <1>
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.108:2376"
export DOCKER_CERT_PATH="/Users/burrsutter/minikube_0.33.1/bin/.minikube/certs"
export DOCKER_API_VERSION="1.35"
# Run this command to configure your shell:
# eval $(minikube --profile 11steps docker-env)
# or
$ eval $(minikube --profile 11steps docker-env)
# and
# eval $(minishift oc-env) <2>
----
<1> This command allows configure your "docker" CLI tool against your minikube or minishift's Docker daemon.  If you are using GKE, AKS, EKS or other, then you will need to "docker push" your image to that platform's favorite image registry. You can also use quay.io as a vendor neutral registry 
<2> This command puts the "oc" CLI tool in your PATH

=== Using Docker CLI 
----
$ docker ps
$ docker images
----
These commands should now be pulling from your minikube/minishift hosted docker daemon.  You can turn off the Docker for Mac/Windows daemon to save memory.


=== Minikube/Minishift Happy?
----
$ minikube --profile 11steps ssh <1>
$ free -h
$ df -h
$ top
$ ctrl-c
$ exit
----
<1> you can shell into your VM and check on resources
